### ISSUE TITLE
The second link in the file, to the ALLFiles content, should be AZ-303ZH

### ISSUE THREAD

**Issue by wbpluto** [MicrosoftLearning/AZ-303ZH-Microsoft-Azure-Architect-Technologies#1]
readme.md and index.md

The link in the file, to the ALLFiles content, should be  
https://github.com/MicrosoftLearning/AZ-303**ZH**-Microsoft-Azure-Architect-Technologies/archive/master.zip

![image](https://user-images.githubusercontent.com/5191513/91556650-a7898e00-e965-11ea-9720-e9b6016d8b15.png)

![image](https://user-images.githubusercontent.com/5191513/91557023-47471c00-e966-11ea-8ba3-60d9f7e314b4.png)

**Comment by VietTran0302** [comment]
fixed
