### ISSUE TITLE
The link in the Readme-Lab List for AZ-303.md file should be AZ-303ZH

### ISSUE THREAD

**Issue by wbpluto** [MicrosoftLearning/AZ-303ZH-Microsoft-Azure-Architect-Technologies#3]
The link in the 'Readme-Lab List for AZ-303.md' file should be AZ-303ZH:

https://github.com/MicrosoftLearning/AZ-303ZH-Microsoft-Azure-Architect-Technologies

![image](https://user-images.githubusercontent.com/5191513/91557572-48c51400-e967-11ea-83b8-b46af34991cc.png)

**Comment by VietTran0302** [comment]
fixed
